baseURL = "http://photodojo.cz/"
languageCode = "en-us"
title = "PhotoDojo.cz"
tags = ["photography", "deliberate practice", "dojo"]
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
# disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "PhotoDojo.cz"
    author = "Dežo Meško"
    description = "Photo Dojo - buď sám svojím trenérem"
    logoBig = "/images/osprey-logo.png"
    logoSmall = "/images/osprey-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "PhotoDojo"
    linkedin = "PhotoDojo"
    github = "PhotoDojo"
    email = "sensei@photodojo.cz"
    googleTagManager = ""
    highlightJS = true
    copyright = false
    credit = false
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "Vize"
    url  = "/#vize"
    weight = 1
[[menu.main]]
    name = "Úvod"
    url  = "/#uvod"
    weight = 2
[[menu.main]]
    name = "Katas"
    url  = "/#katas"
    weight = 3
[[menu.main]]
    name = "Akce"
    url  = "/#akce"
    weight = 4
[[menu.main]]
    name = "Kontakt"
    url  = "/#kontakt"
    weight = 5