baseURL = "https://photodojo.cz/"
languageCode = "en-us"
title = "PhotoDojo.cz"
tags = ["photography", "deliberate practice", "dojo"]
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
# disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "PhotoDojo.cz"
    author = "Dežo Meško"
    description = "Photo Dojo - buď sám svojím trenérem"
    logoBig = "/images/dojo.jpg"
    # logoSmall = "/images/osprey-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/dojo.jpg"
    twitter = "PhotoDojo"
    facebook = "bah"
    # linkedin = "PhotoDojo"
    # github = "PhotoDojo"
    email = "dmesko+dojo@gmail.com"
    # email = "sensei@photodojo.cz"
    googleTagManager = ""
    highlightJS = true
    copyright = false
    credit = false
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "Vize"
    url  = "/#vize"
    weight = 1
[[menu.main]]
    name = "Úvod"
    url  = "/#uvod"
    weight = 2
[[menu.main]]
    name = "Katas"
    url  = "/#katas"
    weight = 3
[[menu.main]]
    name = "Akce"
    url  = "/#akce"
    weight = 4
[[menu.main]]
    name = "Kontakt"
    url  = "/#contact"
    weight = 5